### ISSUE TITLE
Calendar information is not shown on the screen.

### ISSUE THREAD

**Issue by ukiras123** [evancohen/smart-mirror#511]
I configured the calendar but I don't see any events on the screen. Is this a bug or am I doing something wrong?

**Comment by justbill2020** [comment]
@ukiras123 lets discuss this one on [discord chat](https://discord.gg/EMb4ynW) it will be easier to help you in real-time

**Comment by ukiras123** [comment]
sure @justbill2020

**Comment by justbill2020** [comment]
@ukiras123  this is now resolved from working with you on discord.

Thank you.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by ukiras123** [comment]
Thanks for the help

**Comment by justbill2020** [comment]
also turns out this is actually a duplicate as well #513 the issue was caused because the max number of days and max number of events fields were not added in there because the defaults were blank...

**Comment by ItxMuneeb** [comment]
whats the solution? i am still having this problem

i am using this link
https://www.calendarlabs.com/templates/ical/US-Holidays.ics
